[build]
  command = "npm run build"
  publish = "build"  # This should match your production build folder (likely 'build' for React apps)

[context.production.environment]
  NODE_VERSION = "14"  # Specify your desired Node.js version
